# fly.toml app configuration file generated for still-cloud-3849 on 2023-09-14T22:01:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-cloud-3849"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
